from .nodes_a2f import NODE_CLASS_MAPPINGS as _A2F, NODE_DISPLAY_NAME_MAPPINGS as _A2F_N
from .nodes_intent import NODE_CLASS_MAPPINGS as _INT, NODE_DISPLAY_NAME_MAPPINGS as _INT_N
from .nodes_sheet import NODE_CLASS_MAPPINGS as _SHEET, NODE_DISPLAY_NAME_MAPPINGS as _SHEET_N
from .nodes_set import NODE_CLASS_MAPPINGS as _SET, NODE_DISPLAY_NAME_MAPPINGS as _SET_N
from .nodes_block import NODE_CLASS_MAPPINGS as _BLK, NODE_DISPLAY_NAME_MAPPINGS as _BLK_N

NODE_CLASS_MAPPINGS = {**_A2F, **_INT, **_SHEET, **_SET, **_BLK}
NODE_DISPLAY_NAME_MAPPINGS = {**_A2F_N, **_INT_N, **_SHEET_N, **_SET_N, **_BLK_N}
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
