from .nodes_a2f import NODE_CLASS_MAPPINGS as _A2F, NODE_DISPLAY_NAME_MAPPINGS as _A2F_N
from .nodes_intent import NODE_CLASS_MAPPINGS as _INT, NODE_DISPLAY_NAME_MAPPINGS as _INT_N

NODE_CLASS_MAPPINGS = {**_A2F, **_INT}
NODE_DISPLAY_NAME_MAPPINGS = {**_A2F_N, **_INT_N}
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
